//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_RENT_A_CAR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRANCES()
        {
            this.CARS = new HashSet<CARS>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public double Long { get; set; }
        public double Lat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARS> CARS { get; set; }
    }
}
