//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_RENT_A_CAR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR_TYPE()
        {
            this.CARS = new HashSet<CARS>();
        }
    
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public double DailyCost { get; set; }
        public double DailyPenalty { get; set; }
        public int Year { get; set; }
        public int GearType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARS> CARS { get; set; }
    }
}
