//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_RENT_A_CAR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARS
    {
        public string Number { get; set; }
        public int CarType { get; set; }
        public bool Isvalid { get; set; }
        public bool IsFree { get; set; }
        public int Mileage { get; set; }
        public int Branch { get; set; }
        public byte[] Image { get; set; }
    
        public virtual BRANCES BRANCES { get; set; }
        public virtual CAR_TYPE CAR_TYPE { get; set; }
    }
}
